CREATE DATABASE IF NOT EXISTS TODOAPP;

USE TODOAPP;

CREATE TABLE IF NOT EXISTS Users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Tasks (
    task_id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    subtitle VARCHAR(255),
    comments TEXT,
    due_date DATETIME NOT NULL,
    completed BOOLEAN DEFAULT 0,
    user_id INT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES Users(user_id)
);